sonar.projectKey=crmsofterwere
sonar.projectName=CRM Software (Velzon Invoice)
sonar.sourceEncoding=UTF-8

sonar.sources=app,routes,database,config,resources
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**,build/**,resources/lang/**,resources/json/**,resources/fonts/**,resources/images/**

sonar.css.file.suffixes=.scss,.css
